out : main.o functions.o
 	g++ main.o functions.o -o out

main.o : main.cpp
 	g++ -c main.cpp -o main.o

functions.o: functions.cpp
 	g++ -c functions.cpp -o functions.o

clean :
 	rm *.o make
 	
distclean: clean
 	rm Makefile
