TARGET = LR_5
CC=g++
CFLAGS = -c

SOURCES = main.cpp
OBJ = $(SOURCES: .cpp=.o)

all: $(TARGET) 

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

%.o : %.cpp
	$(CC) $(CFLAGS) $< -o $@  
TAGS:   $(SOURCES)
	etags $(SOURCES) 
clean:
	rm -rf *.o $(TARGET)

distclean: clean
	rm -f TAGS Makefile config.status