TARGET = Lab_5
CC=g++
CFLAGS = -c

SOURCES = main.cpp sortint.cpp sortchar.cpp reverse.cpp
OBJ = $(SOURCES: .cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

%.o : %.cpp
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o $(TARGET)